### PR TITLE
Add release tests

### PR DESCRIPTION
**Pull request by blainemotsinger**
This PR adds release tests to verify the version is set on
each file, the changes file contains an entry matching the latest
version, and the manifest is up to date.

Before releasing a new version, these tests can be run by setting
TEST_RELEASE=1 in ENV.

### CODE REVIEW

**Comment by blainemotsinger** [comment]
rebased on updated master

**Comment by blainemotsinger** [comment]
Guess I should have run my own tests XD
Added them to MANIFEST.SKIP to they're not added to the install.

**Comment by cbrandtbuffalo** [comment]
Hi Blaine, thanks for the updates! I'm out for a bit but we'll merge soon.

**Comment by blainemotsinger** [comment]
Happy to contribute!  Hope things are well :)

**Comment by sunnavy** [comment]
Merged accordingly, thanks Blaine!

-sunnavy

**Comment by blainemotsinger** [comment]
commits are now in master branch, closing.

**Pull request closed without merging**
